export const ColumnTypeNames = {
    STRING: 'STRING',
    FOREIGN_KEY: 'FOREIGN_KEY',
    PRIMARY_KEY: 'PRIMARY_KEY',
    DECIMAL: 'DECIMAL',
    BOOL: 'BOOL',
    INTEGER: 'INTEGER',
    DATE_TIME: 'DATE_TIME'
}